create table if not exists public.pact_journal_pacts (
  id bigint generated by default as identity primary key,
  wallet text not null,
  habit_name text not null,
  category text not null default 'unknown',
  frequency_label text not null,
  frequency_code text not null default '0',
  duration_days integer not null check (duration_days > 0),
  stake_amount_wei numeric(78, 0) not null default 0,
  start_at timestamptz not null default timezone('utc', now()),
  last_checkin_at timestamptz,
  completed boolean not null default false,
  reward_claimed boolean not null default false,
  latest_encouragement text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.pact_journal_checkins (
  id bigint generated by default as identity primary key,
  pact_id bigint not null references public.pact_journal_pacts(id) on delete cascade,
  wallet text not null,
  checkin_day date not null,
  checked_at timestamptz not null,
  tx_hash text,
  source text not null default 'checkin',
  encouragement text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint pact_journal_checkins_source_check check (source in ('seed', 'chain-sync', 'checkin')),
  constraint pact_journal_checkins_unique_day unique (pact_id, checkin_day)
);

create index if not exists pact_journal_pacts_wallet_idx
  on public.pact_journal_pacts(wallet);

create index if not exists pact_journal_checkins_wallet_idx
  on public.pact_journal_checkins(wallet);

create index if not exists pact_journal_checkins_pact_checked_at_idx
  on public.pact_journal_checkins(pact_id, checked_at desc);

create or replace function public.set_pact_journal_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_pact_journal_updated_at on public.pact_journal_pacts;

create trigger set_pact_journal_updated_at
before update on public.pact_journal_pacts
for each row
execute function public.set_pact_journal_updated_at();

create or replace function public.reset_pacta_demo_data()
returns void
language plpgsql
security definer
as $$
begin
  truncate table public.pact_journal_checkins restart identity cascade;
  truncate table public.pact_journal_pacts restart identity cascade;

  insert into public.pact_journal_pacts (
    id,
    wallet,
    habit_name,
    category,
    frequency_label,
    frequency_code,
    duration_days,
    stake_amount_wei,
    start_at,
    last_checkin_at,
    completed,
    reward_claimed,
    latest_encouragement
  )
  values
    (
      1,
      '0xde1a000000000000000000000000000000000001',
      '喝水',
      'diet',
      '每天',
      '0',
      21,
      100000000000000000,
      timezone('utc', date_trunc('day', now()) - interval '6 day' + interval '8 hour'),
      timezone('utc', date_trunc('day', now()) + interval '8 hour'),
      false,
      false,
      null
    ),
    (
      2,
      '0xde1a000000000000000000000000000000000001',
      '阅读',
      'mental',
      '工作日',
      '1',
      14,
      500000000000000000,
      timezone('utc', date_trunc('day', now()) - interval '9 day' + interval '8 hour'),
      timezone('utc', date_trunc('day', now()) - interval '2 day' + interval '8 hour'),
      false,
      false,
      null
    );

  insert into public.pact_journal_checkins (pact_id, wallet, checkin_day, checked_at, tx_hash, source, encouragement)
  values
    (1, '0xde1a000000000000000000000000000000000001', current_date - 6, timezone('utc', date_trunc('day', now()) - interval '6 day' + interval '8 hour'), '0x0000000000000000000000000000000000000000000000000000000000001001', 'seed', null),
    (1, '0xde1a000000000000000000000000000000000001', current_date - 3, timezone('utc', date_trunc('day', now()) - interval '3 day' + interval '8 hour'), '0x0000000000000000000000000000000000000000000000000000000000001002', 'seed', null),
    (1, '0xde1a000000000000000000000000000000000001', current_date - 1, timezone('utc', date_trunc('day', now()) - interval '1 day' + interval '8 hour'), '0x0000000000000000000000000000000000000000000000000000000000001003', 'seed', null),
    (1, '0xde1a000000000000000000000000000000000001', current_date, timezone('utc', date_trunc('day', now()) + interval '8 hour'), '0x0000000000000000000000000000000000000000000000000000000000001004', 'seed', null),
    (2, '0xde1a000000000000000000000000000000000001', current_date - 8, timezone('utc', date_trunc('day', now()) - interval '8 day' + interval '8 hour'), '0x0000000000000000000000000000000000000000000000000000000000002001', 'seed', null),
    (2, '0xde1a000000000000000000000000000000000001', current_date - 7, timezone('utc', date_trunc('day', now()) - interval '7 day' + interval '8 hour'), '0x0000000000000000000000000000000000000000000000000000000000002002', 'seed', null),
    (2, '0xde1a000000000000000000000000000000000001', current_date - 5, timezone('utc', date_trunc('day', now()) - interval '5 day' + interval '8 hour'), '0x0000000000000000000000000000000000000000000000000000000000002003', 'seed', null),
    (2, '0xde1a000000000000000000000000000000000001', current_date - 2, timezone('utc', date_trunc('day', now()) - interval '2 day' + interval '8 hour'), '0x0000000000000000000000000000000000000000000000000000000000002004', 'seed', null);

  perform setval(
    pg_get_serial_sequence('public.pact_journal_pacts', 'id'),
    coalesce((select max(id) from public.pact_journal_pacts), 1),
    true
  );

  perform setval(
    pg_get_serial_sequence('public.pact_journal_checkins', 'id'),
    coalesce((select max(id) from public.pact_journal_checkins), 1),
    true
  );
end;
$$;
